// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/gin-gonic/gin"
	"lintangbs.org/lintang/template/app/start"
	"lintangbs.org/lintang/template/config"
)

// Injectors from wire.go:

func InitApp(cfg *config.Config, handler *gin.Engine) *start.InitWireApp {
	initWireApp := start.InitHTTPandGRPC(cfg, handler)
	return initWireApp
}
