app:
  name: 'go-monitor-api'
  version: '1.0.0'

http:
  port: '8080'

logger:
  level: 'debug'
  filename: 'go-monitor-api'
  max_age: 30
  max_backups: false

postgres:
  pool_max: 2
  username: postgres
  password: pass



redis:
  server_address: ':6379'
  host: chat-redispkg #gak guna
  address: 6379 #gak guna
  password: passwordRedis #gak guna
