version: '3.9'
services:

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'postgres'
    ports:
      - 5432:5432

  pg-admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - 5050:5050



  redis:
    image: redis:7.0.1-alpine3.16
    container_name: redispkg
    hostname: redispkg
    restart: always
    ports:
      - 6379:6379
    command: >
      --requirepass passwordRedis


volumes:
  pg-data:
